name    'erwbgy-tomcat'
version '0.1.1'
source 'https://github.com/erwbgy/puppet-tomcat.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Run Tomcat instances under Runit'
description 'Run Tomcat instances under Runit'
project_page 'http://forge.puppetlabs.com/erwbgy/tomcat'
dependency 'erwbgy/runit', '>= 0.2.1'
