name    'erwbgy-logstash'
version '0.1.1'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Install the logstash agent with a configuration file.'
project_page 'https://github.com/erwbgy/puppet-logstash'
